/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import <Foundation/NSObject.h>

@class NSData;

@interface CKImageData : NSObject {
	// CGImageSourceRef _imageSource; < iOS9
	CAImageQueueRef _imageSource; // >= iOS9
	NSData* _data;
}
@property(readonly, assign, nonatomic) NSData* data;
-(id)initWithData:(id)data;
-(void)dealloc;
-(id)image;
-(id)imageWithMaxLength:(int)maxLength;
-(id)jpegDataWithMaxLength:(int)maxLength compression:(float)compression;
-(id)pngDataWithMaxLength:(int)maxLength;
-(id)mimeType;
-(id)imageType;
-(int)imageCount;
-(CGSize)size;
-(int)imageOrientation;
// -(CGImageSourceRef)_imageSource; < iOS 9
-(CAImageQueueRef)_imageSource; // >= iOS9
-(id)_newImageWithMaxLength:(int)maxLength transformOrientation:(BOOL)orientation;
-(CGImageRef)_newCGImageWithMaxLength:(int)maxLength transformOrientation:(BOOL)orientation;
@end

